---
- name: Create 3par CPG
  hosts: localhost
  become: no
  environment:
    #comment out no_proxy if not behind proxy
    no_proxy: localhost, 10.10.1.150, 10.10.1.151

  vars:
    rest_api_url_3par: "https://{{ ip_address_3par }}:8080/api/v1"

    #   OPTIONS for LDLayout -
    #  'cpg_raid_type': 1     - RAID 0         'cpg_HA_type': 1    - PORT: Support failure of a port.
    #  'cpg_raid_type': 2     - RAID 1         'cpg_HA_type': 2    - CAGE: Support failure of a drive cage.
    #  'cpg_raid_type': 3     - RAID 5         'cpg_HA_type': 3    - MAG: Support failure of a drive magazine.
    #  'cpg_raid_type': 4     - RAID 6

    cpg_raid_type: 4
    cpg_HA_type: 3

  vars_prompt:
    - name: "auth_3par_user"
      prompt: "Enter 3par admin user"
      private: no
      default: "3paradm"

    - name: "auth_3par_password"
      prompt: "Enter password"
      private: yes
      default: "3pardata"

    - name: "ip_address_3par"
      prompt: "3PAR Storage System IP address"
      private: no
      default: "10.10.1.150"

    - name: "cpg_name"
      prompt: "Enter CPG name"
      private: no
      default: "FC_r6"

    - name: "size_GiB"
      prompt: "Enter growth size in GiB"
      private: no
      default: "32"


  tasks:
    - name: check if 3par WSAPI is running
      uri:
        url: "{{ rest_api_url_3par }}/credentials"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{ 'user': '{{ auth_3par_user }}', 'password': '{{ auth_3par_password }}' }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: output

    - name: Parsing key
      debug:
        msg: "{{ output.json.key }}"

    - name: Create 3par CPG
      uri:
        url: "{{ rest_api_url_3par }}/cpgs"
        method: POST
        headers:
          Content-Type: "application/json"
          X-HP3PAR-WSAPI-SessionKey: "{{ output.json.key }}"
          Accept: "application/json"
        body_format: json
        body: "{ 'name': '{{ cpg_name }}','LDLayout': {'RAIDType': {{ cpg_raid_type }},'HA': {{ cpg_HA_type }}},'growthIncrementMiB': {{ size_GiB|int * 1024 }} }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: volume_output

    - name: Parsing CPG status
      debug:
        msg: "{{ volume_output }}"
