---
- name: New 3par Host - Fibre Channel
  hosts: localhost
  become: no
  environment:
    #comment out no_proxy if not behind proxy
    no_proxy: localhost, 10.10.1.150, 10.10.1.151

  vars:
    rest_api_url_3par: "https://{{ ip_address_3par }}:8080/api/v1"

  vars_prompt:
    - name: "auth_3par_user"
      prompt: "Enter 3par admin user"
      private: no
      default: "3paradm"

    - name: "auth_3par_password"
      prompt: "Enter password"
      private: yes
      default: "3pardata"

    - name: "ip_address_3par"
      prompt: "3PAR Storage System IP address"
      private: no
      default: "10.10.1.150"

    - name: "new_host_name"
      prompt: "Specify new 3PAR host"
      private: no

    - name: "host_persona"
      prompt: "Specify host persona"
      private: no
      default: "11"

    - name: "fc_wwns"
      prompt: "Enter FC WWNs (separate multiple entries with comma)"
      private: no
      default: '"10:00:00:00:c9:22:fc:01", "10:00:00:00:c9:22:fc:02"'



  tasks:
    - name: check if 3par WSAPI is running
      uri:
        url: "{{ rest_api_url_3par }}/credentials"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{ 'user': '{{ auth_3par_user }}', 'password': '{{ auth_3par_password }}' }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: output

    - name: Parsing key
      debug:
        msg: "{{ output.json.key }}"

    - name: Create 3PAR host - Fibre Channel
      uri:
        url: "{{ rest_api_url_3par }}/hosts"
        method: POST
        headers:
          Content-Type: "application/json"
          X-HP3PAR-WSAPI-SessionKey: "{{ output.json.key }}"
          Accept: "application/json"
        body_format: json
        body: "{ 'name': '{{ new_host_name }}','persona': {{ host_persona }},'FCWWNs':[ {{ fc_wwns }} ]}"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: host_output

    - name: Create 3PAR host status
      debug:
        msg: "{{ host_output }}"

    - name: release authentication key
      uri:
        url: "{{ rest_api_url_3par }}/credentials/{{ output.json.key }}"
        method: DELETE
        headers:
          Content-Type: "application/json"
        validate_certs: no
