---
- name: New 3par Volume
  hosts: localhost
  become: no
  environment:
    #comment out no_proxy if not behind proxy
    no_proxy: localhost, 10.10.1.150, 10.10.1.151

  vars:
    rest_api_url_3par: "https://{{ ip_address_3par }}:8080/api/v1"

  vars_prompt:
    - name: "auth_3par_user"
      prompt: "Enter 3par admin user"
      private: no
      default: "3paradm"

    - name: "auth_3par_password"
      prompt: "Enter password"
      private: yes
      default: "3pardata"

    - name: "ip_address_3par"
      prompt: "3PAR Storage System IP address"
      private: no
      default: "10.10.1.150"

    - name: "vol_name"
      prompt: "Enter new volume name"
      private: no

    - name: "cpg_name"
      prompt: "Enter CPG name"
      private: no
      default: "FC_r6"

    - name: "size_GiB"
      prompt: "Enter Size in GiB"
      private: no


  tasks:
    - name: check if 3par WSAPI is running
      uri:
        url: "{{ rest_api_url_3par }}/credentials"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{ 'user': '{{ auth_3par_user }}', 'password': '{{ auth_3par_password }}' }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: output

    - name: Parsing key
      debug:
        msg: "{{ output.json.key }}"

    - name: Create 3par volume
      uri:
        url: "{{ rest_api_url_3par }}/volumes"
        method: POST
        headers:
          Content-Type: "application/json"
          X-HP3PAR-WSAPI-SessionKey: "{{ output.json.key }}"
          Accept: "application/json"
        body_format: json
        body: "{ 'name': '{{ vol_name }}','cpg': '{{ cpg_name }}','sizeMiB': {{ size_GiB|int * 1024 }} }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: volume_output

    - name: Parsing Volumes GET
      debug:
        msg: "{{ volume_output }}"
