---
- name: Unexport volume from hostset
  hosts: localhost
  become: no
  environment:
    #comment out no_proxy if not behind proxy
    no_proxy: localhost, 10.10.1.150, 10.10.1.151

  vars:
    rest_api_url_3par: "https://{{ ip_address_3par }}:8080/api/v1"

  vars_prompt:
    - name: "auth_3par_user"
      prompt: "Enter 3par admin user"
      private: no
      default: "3paradm"

    - name: "auth_3par_password"
      prompt: "Enter password"
      private: yes
      default: "3pardata"

    - name: "ip_address_3par"
      prompt: "3PAR Storage System IP address"
      private: no
      default: "10.10.1.150"

    - name: "vol_name"
      prompt: "Enter volume to unexport"
      private: no
      default: "ansi_vol"

    - name: "hostset_name"
      prompt: "Enter hostset to unexport volume"
      private: no
      default: "virtware-mgmt"

    - name: "lun_id"
      prompt: "Enter LUN ID"
      private: no
      default: "34"


  tasks:
    - name: check if 3par WSAPI is running
      uri:
        url: "{{ rest_api_url_3par }}/credentials"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{ 'user': '{{ auth_3par_user }}', 'password': '{{ auth_3par_password }}' }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: output

    - name: Parsing key
      debug:
        msg: "{{ output.json.key }}"

    - name: Unexport volume to hostset
      uri:
        url: "{{ rest_api_url_3par }}/vluns/{{ vol_name }},{{ lun_id }},set:{{ hostset_name }}"
        method: DELETE
        headers:
          Content-Type: "application/json"
          X-HP3PAR-WSAPI-SessionKey: "{{ output.json.key }}"
          Accept: "application/json"
        status_code: 200
        return_content: yes
        validate_certs: no
      register: vlun_output

    - name: Parsing VLUN Status
      debug:
        msg: "{{ vlun_output }}"

    - name: release authentication key
      uri:
        url: "{{ rest_api_url_3par }}/credentials/{{ output.json.key }}"
        method: DELETE
        headers:
          Content-Type: "application/json"
        validate_certs: no
