---
- name: Create 3par Volume Snapshot
  hosts: localhost
  become: no
  environment:
    #comment out no_proxy if not behind proxy
    no_proxy: localhost, 10.10.1.150, 10.10.1.151

  vars:
    rest_api_url_3par: "https://{{ ip_address_3par }}:8080/api/v1"

  vars_prompt:
    - name: "auth_3par_user"
      prompt: "Enter 3par admin user"
      private: no
      default: "3paradm"

    - name: "auth_3par_password"
      prompt: "Enter password"
      private: yes
      default: "3pardata"

    - name: "ip_address_3par"
      prompt: "3PAR Storage System IP address"
      private: no
      default: "10.10.1.150"

    - name: "vol_name"
      prompt: "Enter volume name to snapshot"
      private: no
      default: "ansi_vol"

    - name: "snap_name"
      prompt: "Enter snapshot name"
      private: no
      default: "ansi_vol_snap"

    - name: "read_only"
      prompt: "true/false"
      private: no
      default: "false"

    - name: "snap_comment"
      prompt: "Comment"
      private: no
      default: ""

  tasks:
    - name: check if 3par WSAPI is running
      uri:
        url: "{{ rest_api_url_3par }}/credentials"
        method: POST
        headers:
          Content-Type: "application/json"
        body_format: json
        body: "{ 'user': '{{ auth_3par_user }}', 'password': '{{ auth_3par_password }}' }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: output

    - name: Parsing key
      debug:
        msg: "{{ output.json.key }}"

    - name: Create 3par Volume Snapshot
      uri:
        url: "{{ rest_api_url_3par }}/volumes/{{ vol_name }}"
        method: POST
        headers:
          Content-Type: "application/json"
          X-HP3PAR-WSAPI-SessionKey: "{{ output.json.key }}"
          Accept: "application/json"
        body_format: json
        body: "{ 'action':'createSnapshot','parameters': {'name': '{{ snap_name }}','readOnly':{{ read_only }},'comment': '{{ snap_comment }}'} }"
        status_code: 201
        return_content: yes
        validate_certs: no
      register: snapshot_output

    - name: Parsing Snapshot status
      debug:
        msg: "{{ snapshot_output }}"
